export {
	type RelationType,
	type ScalarFieldDef,
	type HasOneRelationDef,
	type HasManyRelationDef,
	type HasManyRelationKind,
	type FieldDef,
	type EntitySchemaDef,
	type SchemaDefinition,
	type InferModel,
	type InferEntityNames,
	type EntityDef,
	type InferEntityDef,
	type EnumFieldDef,
	scalar,
	enumScalar,
	hasOne,
	hasMany,
	defineSchema,
	entityDef,
	roleEntityDef,
} from '@contember/bindx-client'
